# Generated by Django 4.2.8 on 2023-12-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SavorySketch_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', through='SavorySketch_api.RecipeIngredient', to='SavorySketch_api.ingredient'),
        ),
        migrations.AlterField(
            model_name='savoryuser',
            name='profile_img',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
