# Generated by Django 4.2.8 on 2023-12-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SavorySketch_api', '0003_recipe_measurements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_on', to='SavorySketch_api.measurement'),
        ),
    ]
